info:
  id: proftpd-config
  name: ProFTPD Configuration File - Detect
  author: drfabiocastro
  description: Template to detect ProFTPD configuration files
  severity: High
  classification:
    country: any
  tags:
    - proftpd
    - configuration
    - file

  matcher-condition: and

  requests:
    method: GET
    path:
      - "/proftpd.conf"
      - "/proftpd/proftpd.conf"
    description: Example requests to trigger detection

  matchers:
    - pattern: "ProFTPD"
      type: body
      description: ProFTPD server software found in response body
    - pattern: "DefaultRoot"
      type: body
      description: DefaultRoot directive found in response body
    - pattern: "AllowUser"
      type: body
      description: AllowUser directive found in response body

  response:
    - status:
        - 200
        - 401
        - 403
      description: Successful response status or authentication required
