info:
  id: symfony-database-config
  name: Symfony Database Configuration - Detect
  author: drfabiocastro
  description: Template to detect Symfony database configuration exposure
  severity: High
  classification:
    country: any
  tags:
    - symfony
    - database
    - credentials
    - exposure

  matcher-condition: and

  requests:
    method: GET
    path:
      - "/config/databases.yml"
      - "/app/config/databases.yml"
      - "/app/config/parameters.yml"
      - "/app/config/parameters.yml.dist"
    description: Example request to trigger detection

  matchers:
    - pattern: "database_host"
    - pattern: "database_port"
    - pattern: "database_name"
    - pattern: "database_user"
    - pattern: "database_password"
      type: body
      description: Symfony database configuration found in response body

  response:
    - status:
      - 200
      - 401
      - 403
      description: Successful response status or authentication required